import { commonDirComments } from "../tree/constants";

/** Retrieves the auto generated comments for common folders
 * @param {string} path path of the specific folder like src
 * @returns {string} The pre-defined Comment for the folder like "# Source files"
 */

export const getAutoGeneratedCommentForPath = (path: string): string => {
  const comment = `${commonDirComments[path] ?? ""}`;
  return comment;
};

export default getAutoGeneratedCommentForPath;
