import { expect } from "chai";
import getAutoGeneratedCommentForPath from "./getAutoGeneratedCommentForPath";

describe("getAutoGeneratedCommentForPath Function", () => {
  it("Should retrieve the auto generated comment for common folder", () => {
    const result = getAutoGeneratedCommentForPath("src");
    expect(result).to.equal("# Source files");
  });
});
